name: test:e2e

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'pull repo'
        uses: actions/checkout@v2
      - name: 'setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn run e2e